### ISSUE TITLE
(Windows) Test and build scripts fail

### ISSUE THREAD

**Issue by tylersticka** [cloudfour/drizzle-builder#98]
These scripts fail, even if the builder works just fine within the context of a Drizzle project.

My best guess is that the `env` stuff isn't terribly cross-platform.

**Comment by tylersticka** [comment]
Although Drizzle is now running fine on Windows for me (see https://github.com/cloudfour/drizzle/issues/74), this issue is unresolved.

Running `npm install` and then `npm run build` appears to work fine... several files compile to `dist` and everything looks okay. But `npm test` still outputs errors:

```
> drizzle-builder@0.0.10 test D:\Data\Source\drizzle-builder
> npm run build; env DRIZZLE_DEBUG=1 mocha --recursive

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\tyler\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "build;" "env" "DRIZZLE_DEBUG=1" "mocha" "--recursive"
npm ERR! node v4.2.1
npm ERR! npm  v3.3.10

npm ERR! missing script: build;
npm ERR!
npm ERR! If you need help, you may report this error at:
npm ERR!     <https://github.com/npm/npm/issues>

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Data\Source\drizzle-builder\npm-debug.log

npm ERR! Windows_NT 10.0.14393
npm ERR! argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Users\\tyler\\AppData\\Roaming\\npm\\node_modules\\npm\\bin\\npm-cli.js" "run" "test"
npm ERR! node v4.2.1
npm ERR! npm  v3.3.10
npm ERR! code ELIFECYCLE
npm ERR! drizzle-builder@0.0.10 test: `npm run build; env DRIZZLE_DEBUG=1 mocha --recursive`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the drizzle-builder@0.0.10 test script 'npm run build; env DRIZZLE_DEBUG=1 mocha --recursive'.
npm ERR! Make sure you have the latest version of node.js and npm installed.
npm ERR! If you do, this is most likely a problem with the drizzle-builder package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     npm run build; env DRIZZLE_DEBUG=1 mocha --recursive
npm ERR! You can get their info via:
npm ERR!     npm owner ls drizzle-builder
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     D:\Data\Source\drizzle-builder\npm-debug.log
```

I then came across this similar-sounding issue: https://github.com/npm/npm/issues/4040#issuecomment-59899798

Replacing the semicolon with `&&` in the `test` script does indeed allow it to run. This time, there are failing tests related to output path testing, presumably because of differences between Windows and Unix paths. The output is far too long to include all of, but here's an example:

```
  1) utils/shared resourcePath should build a resource path from an ID:

      AssertionError: expected 'bar\\baz\\ding\\dong.html' to equal 'bar/baz/ding/dong.html'
      + expected - actual

      -bar\baz\ding\dong.html
      +bar/baz/ding/dong.html

      at Context.<anonymous> (D:\Data\Source\drizzle-builder\test\utils\shared.js:50:28)
      at callFn (D:\Data\Source\drizzle-builder\node_modules\mocha\lib\runnable.js:326:21)
      at Test.Runnable.run (D:\Data\Source\drizzle-builder\node_modules\mocha\lib\runnable.js:319:7)
      at Runner.runTest (D:\Data\Source\drizzle-builder\node_modules\mocha\lib\runner.js:422:10)
      at D:\Data\Source\drizzle-builder\node_modules\mocha\lib\runner.js:528:12
      at next (D:\Data\Source\drizzle-builder\node_modules\mocha\lib\runner.js:342:14)
      at D:\Data\Source\drizzle-builder\node_modules\mocha\lib\runner.js:352:7
      at next (D:\Data\Source\drizzle-builder\node_modules\mocha\lib\runner.js:284:14)
      at Immediate._onImmediate (D:\Data\Source\drizzle-builder\node_modules\mocha\lib\runner.js:320:5)
```

**Comment by erikjung** [comment]
Resolved via https://github.com/cloudfour/drizzle-builder/issues/101
